version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user_metrics
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: metrics_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://user_metrics:securepassword@db:5432/metrics_db
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  pgdata:
    driver: local
